### ISSUE TITLE
Agent doesn't really handle exceptions

### ISSUE THREAD

**Issue by halcwb** [rommsen/EventSourcing-DIY#2]
I have been looking at the `Agent` implementation of the `MailboxProcessor`:

```
        let inbox = new MailboxProcessor<'T>(fun _ ->
            async {
              // Run the user-provided function & handle exceptions
              try return! f self
              with e -> errorEvent.Trigger(e)
            })
```

I noticed that in your EventStore you still need to wrap your code in a try with construct. Otherwise the error will indeed reach the `Agent` code, but this will only propagate the error to error listeners, but the agent will still 'die'. 

How to solve this, I haven't figured out as the implementation needs to recurse on the start function to stay alive.

**Comment by rommsen** [comment]
Hi @halcwb,

yes the Agent dies but without this implementation the whole system would come to a stop and we had no way to recover from this.

The idea in my approach is to have some kind of a supervisor that can detect a fatal error and can then decide to restart the event store or stop the whole system (e.g. restart 3 times within 60 seconds, otherwise stop). If you have a look at the [`EventSourced`](https://github.com/rommsen/EventSourcing-DIY/blob/master/EventSourced/Infrastructure/EventSourced.fs) object it has all the possibilities to do this.
It is not given a initialized event store but instead it is given the `initialize` function so it can decide whether it wants to restart it, when it detects an error.
```F#
// use the init function
let eventStore = configuration.EventStoreInit eventStorage

// do something when error occurs
eventStore.OnError.Add(fun exn -> Helper.printError (sprintf "EventStore Error: %s" exn.Message) exn)
```

If you want to have an Agent that is restarting itself you can have a look at this implementation: https://github.com/rommsen/EventSourcing-DIY/blob/master/EventSourced/Infrastructure/EventSourced.fs

If you wanted to have more control you would need a more sophisitcated actor model framework like Akka.net

**Comment by halcwb** [comment]
Thanks!
