### ISSUE TITLE
Adding truck 2 with wrong source

### ISSUE THREAD

**Issue by halcwb** [rommsen/EventSourcing-DIY#4]
In your code you add truck 2 with the wrong source:
`
     ("Add_truck_to_fleet truck2", fun () -> Add_truck_to_fleet truck2 |> app.HandleCommand truck1_guid |> runAsync |> printCommandResults "Command")`

As a side note, this is also what I am struggling a bit with. It seems that the infrastructure is leaking through the code and that this results in errors like the one above which are quite difficult to recognize. In this example the HandleCommand depends on the eventsource, but the eventsource as a domain concept has no particular meaning. Rather you would like to be able to just add the truck to the fleet. 

Also, what about nested aggregates? For example the truck gets lists of orders that consists of different flavors. Then the truck is the top level domain entity for orders and each order is a top level domain entity for the individual flavor lines.

**Comment by rommsen** [comment]
> 
> 
> In your code you add truck 2 with the wrong source:
> ` ("Add_truck_to_fleet truck2", fun () -> Add_truck_to_fleet truck2 |> app.HandleCommand truck1_guid |> runAsync |> printCommandResults "Command")`
>
Yes you are right, thanks.

>
> As a side note, this is also what I am struggling a bit with. It seems that the infrastructure is leaking through the code and that this results in errors like the one above which are quite difficult to recognize. In this example the HandleCommand depends on the eventsource, but the eventsource as a domain concept has no particular meaning. Rather you would like to be able to just add the truck to the fleet.
>
`EventSource` is not a domain concept but a concept within the infrastructure (same as the `CommandHandler`. It is the source for a specific stream of events. Most of the time it is the Id of the aggregate root. You do not find it within the domain (have a look at the `behaviour` function), so imho it is not leaking. There you only find trucks etc. Therefore you need to translate between `EventSource` and `Truck`.

> 
> Also, what about nested aggregates? For example the truck gets lists of orders that consists of different flavors. Then the truck is the top level domain entity for orders and each order is a top level domain entity for the individual flavor lines.
>
Can you describe the problem here? Nested aggregates do not exist. To use normal DDD language: Within an aggregate you can find multiple entities (things that have an identity/a lifecycle and can be created, deleted etc). One of those entities is the aggregate root, so it is the only entry point for your aggregate. You also have value objects, so things that are identified by its values, not by its identity (I do not borrow you a specific 5 € note, just the value is important). In your example flavours are just value objects. Maybe a use case needs flavours to be entities? You have just learned something about your domain. A good chance to remodel your stuff.

**Comment by halcwb** [comment]
I think I am getting a better grasp on this. See my latest [commit](https://github.com/halcwb/InformedICU/blob/40280bdca366998838cb8b4c9b03942ef136feca/Scripts.fsx). I am trying to combine your setup of event sourcing with the [domain modelling](https://fsharpforfunandprofit.com/books/) as explained by Scott Wlaschin. I think this will be a nice fit.
