### ISSUE TITLE
Use of projections in read models

### ISSUE THREAD

**Issue by halcwb** [rommsen/EventSourcing-DIY#6]
This is something I burned my fingers on. I used a projection in a read-model and this didn't go well. What happened is that I had these projections:

```
            let updateRegisteredPatients (set: Set<_>) event =
                match event with
                | Registered pat ->
                    pat |> set.Add
                | _ -> set

            let registerdPatients =
                {
                    Init = Set.empty
                    Update = updateRegisteredPatients
                }

            let admittedPatients events =
                let registered = 
                    events 
                    |> (Projection.project registerdPatients)
                    |> Set.toList

                events
                |> List.fold (fun acc e ->
                    match e with
                    | Admitted hn ->
                        match registered 
                              |> List.tryFind (fun pat -> pat.HospitalNumber = hn) with
                        | Some pat -> acc |> List.append [ pat ]
                        | None -> acc
                    | _ -> acc
                ) []

```

So, the `admittedPatients` expects all events to reconstruct which registered patients are admitted. So far so good. But then I used these projections to create readmodels:

```
            let registered () : ReadModel<_, _> =
                let updateState state evs =
                    evs
                    |> List.fold (Projection.intoMap Projections.registerdPatients) 
                                 state

                ReadModel.inMemory updateState Map.empty


            let admitted () : ReadModel<_, _> =
                let updateState state evs =
                    evs
                    |> Event.asEvents
                    |> Projections.admittedPatients
                    |> List.append state

                ReadModel.inMemory updateState []

```
And then things fall apart. The read model only receives the new events. So, when a patient is admitted, only the admitted event is passed to the readmodel. This works fine for the registered patients read model, but the admitted patients read model passes these admitted events to the `admittedPatients` projection that will always return an empty list, as it cannot reconstruct the registered patients.

This was quite hard to detect (meaning it took me more than half an hour). And generally, I try to avoid these kind of errors like the plague. So, my inclination now is to completely separate the event handling and projection logic from the read model logic and not to use projections in readmodels.

**Comment by halcwb** [comment]
I think that there is something fundamentally wrong with the setup that a command and events are used to model behavior. The events can only be interpreted by projections but doesn't this violate the whole concept of CQRS? So instead of Command -> Events -> Events, shouldn't it just be Command -> Events? 

If the workflow needs some form of state, this could be contained by the command. For example the Add_truck_to_fleet fleet command could be modeled like:

Add_truck_to_fleet (truckToAdd, trucksInFleet) 

The trucksInFleet are determined by using a projection/read model. Then there is a real separation between the command generating and writing events and projection/reading these event. 

Alternatively, the Add_truck_to_fleet workflow can issue a query to the read model to get the trucks already in the fleet. But I would prefer the first approach as it is very specific about what is needed for the workflow logic.

**Comment by rommsen** [comment]
Hi there,

sorry for not replying earlier. I was on vacation. 

I think there are some fundamental misunderstandings on how event sourcing and cqrs work. I try my best to clear things up.

At first some short explanation of concepts
### projection 
* function from a state and an event to another state. 
* when a list of events needs to be projected into a specific state you can use a fold with an initial state.

### read model
* most of the time persistent (in memory or stored somewhere) data structure that is able to anwer questions for a specific use case
* listens to new events and uses its current state and those new events to update its current state. most of the time a projection can be used for this

>
> And then things fall apart. The read model only receives the new events. So, when a patient is admitted, only the admitted event is passed to the readmodel. This works fine for the registered patients read model, but the admitted patients read model passes these admitted events to the admittedPatients projection that will always return an empty list, as it cannot reconstruct the registered patients.
>
I really dont see the problem here. A read model should never (except when its rebuild, e.g. at server start when in memory) have to replay all the events. It should hold its current state and only process the new events. That is the sole purpose of a read model. Otherwise it is just a projection. In your examples there is no mechanism to subscribe to new events and hold the current state. I have not touched this in the videos, yet.

> 
> 
> I think that there is something fundamentally wrong with the setup that a command and events are used to model behavior. The events can only be interpreted by projections but doesn't this violate the whole concept of CQRS?
>

no it does not. CQRS means that we have different models for our read side and our write side. For the write side we use events. To be able to decide whether we are allowed to make a state change (i.e. do an action) we need the current state based on the current events. A projection function can be used for this. In OOP system most of the time a class with a replay method is used. In FP we dont need this.
I think you are confusing projections with the read side. Projections are used to build some state from events. They are not read nor write specific. They are just a tool to get a state from events.
The read side can be any easily queryable data structure that we are building for specific use cases. Most of the times it is persistent so we dont need to run through all the events again.

A command can always be rejected. We are just requesting the system to do something. An event is a description of something that happened in our system.  When doing event sourcing events are the single source of truth in out system so Command + current events + some mechanism to get a decidable state out of those events (i.e. a projection or an object with a replay method) resulting in some new events is a perfect way of modelling behavior in those systems.

> So instead of Command -> Events -> Events, shouldn't it just be Command -> Events?
> 
> If the workflow needs some form of state, this could be contained by the command. For example the Add_truck_to_fleet fleet command could be modeled like:
> 
> Add_truck_to_fleet (truckToAdd, trucksInFleet)
> 
> The trucksInFleet are determined by using a projection/read model. Then there is a real separation between the command generating and writing events and projection/reading these event.
> 
please never do this. You completely loose the single source of truth (the event stream) for your business decisions. From where do you get the state for your commands? If you store your events you need to project into a state anyway. But if you have a multiuser system you will run into all kinds of race conditions and faulty states because of eventual consistency. The readmodels might not be updated etc. *This is a very bad idea*

Hope this helps

**Comment by halcwb** [comment]
I confused projections with read models, Still with a the implementation were I used projection to calculate the command arguments,  I was way faster than with directly streaming the aggregate events to the behavior logic. I have to further chew on that.
